# Site settings
title: Michal Kordas Blog
email: me@michalkordas.com
description: >
  I'm quality maniac with passion about Java, Groovy, JVM and fancy tools
  that help to test code in smart, fluent and expressive way. I love bringing
  feedback loops to the micro-level. My main area of interest is Agile Testing.
  Currently I'm working as a fully cross-functional member of a strongly agile
  team as a developer and a „quality guard” with particular focus on
  well-written code, good requirements and efficient process. Unlike majority of
  QA’s, I believe that being a truly good QA engineer means being, first of all,
  a software developer that has all the knowledge needed to deliver
  production-quality code with some additional quality-related skills.
baseurl: ""
url: "http://mkordas.github.io"
twitter_username: michal_kordas
github_username:  mkordas

# Build settings
markdown: kramdown
