# Site settings
title: Michal Kordas Blog
email: me@michalkordas.com
description: >
  Blog about Java, Groovy, JVM, IntelliJ IDEA and bringing feedback loops to the
  micro-level.
baseurl: ""
url: "http://michalkordas.com"
twitter_username: michal_kordas
github_username: mkordas

highlighter: pygments

# Build settings
markdown: kramdown
