# Site settings
title: Michal Kordas Blog
email: me@michalkordas.com
description: >

baseurl: ""
url: "http://mkordas.github.io"
twitter_username: michal_kordas
github_username:  mkordas

# Build settings
markdown: kramdown
